# Assignment: Preparing Data for Analysis (Modified Titanic)

![](https://github.com/kaopanboonyuen/2110446_DataScience_2021s2/raw/main/%20files/hw.png)

In [443]:
#Import the libraries
import numpy as np
import pandas as pd

In [444]:
df = pd.read_csv('https://github.com/kaopanboonyuen/2110446_DataScience_2021s2/raw/main/datasets/hw/titanic_training_dataset_v2.csv')

In [445]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0.0,3.0,"Braund, Mr. Owen Harris",male,22.0,1.0,0,A/5 21171,7.2500,NaN,S
1,2,1.0,1.0,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1.0,0,PC 17599,71.2833,C85,C
2,3,1.0,3.0,"Heikkinen, Miss. Laina",female,26.0,0.0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1.0,1.0,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1.0,0,113803,53.1000,C123,S
4,5,0.0,3.0,"Allen, Mr. William Henry",male,35.0,0.0,0,373450,8.0500,NaN,S

In [446]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     865 non-null    float64
 2   Pclass       828 non-null    float64
 3   Name         866 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        858 non-null    float64
 7   Parch        891 non-null    int64
 8   Ticket       852 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     803 non-null    object
dtypes: float64(5), int64(2), object(5)
memory usage: 83.7+ KB

# 1) Load data & review the data

<font color='blue'>Q1) What is the shape of this dataset? (rows & columns)</font>

In [447]:
df.shape #get row and column of dataset

(891, 12)

# 2) Drop unqualified variables

*   Drop variables with missing > 50%
*   Drop categorical variables with flat values > 70% (variables with the same value in the same column)

<font color='blue'>Q2) How many columns do we have left?</font>

In [448]:
df.dropna(thresh=(len(df)/2),axis=1,inplace=True) #drop column that have missing value more than 50%
df_category = df[["Name","Sex","Ticket","Embarked"]] #select category variable
column_percentage = df_category.apply(lambda x: x.value_counts(normalize=True).max())
column_drop = column_percentage[column_percentage > 0.7].index #drop variable with flat values > 70%

df = df.drop(columns=column_drop)
df.shape[1]

10

# 3) Remove all rows with missing target (the variable "Survived")

<font color='blue'>Q3) How many rows do we have left?</font>

In [449]:
df.dropna(subset="Survived",inplace=True) #remove row that column survived is null
df.shape[0] #display number of row without missing target

865

# 4) Handle outliers

For the variable “Fare”, replace outlier values with the boundary values


*   If value < (Q1 - 1.5IQR), relace with (Q1 - 1.5IQR)
*   If value > (Q3 + 1.5IQR), relace with (Q3 + 1.5IQR)

<font color='blue'>Q4) What is the mean of “Fare” after replacing the outliers (round 2 decimal points)?</font>

In [450]:
#calculate Q1,Q3 and IQR for column Fare
quantile_1 = df["Fare"].quantile(0.25)
quantile_3 = df["Fare"].quantile(0.75)
iqr = quantile_3 - quantile_1

#calculate lower_bound and upper_bound for outlier replacement
lower_bound = quantile_1 - (1.5 * iqr)
upper_bound = quantile_3 + (1.5 * iqr)

df.loc[df.Fare < lower_bound , "Fare"] = lower_bound #replaced outlier by lower_bound
df.loc[df.Fare > upper_bound , "Fare"] = upper_bound #replaced outlier by upper_bound
df #show table

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare
0,1,0.0,3.0,"Braund, Mr. Owen Harris",male,22.0,1.0,0,A/5 21171,7.2500
1,2,1.0,1.0,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1.0,0,PC 17599,65.6563
2,3,1.0,3.0,"Heikkinen, Miss. Laina",female,26.0,0.0,0,STON/O2. 3101282,7.9250
3,4,1.0,1.0,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1.0,0,113803,53.1000
4,5,0.0,3.0,"Allen, Mr. William Henry",male,35.0,0.0,0,373450,8.0500
...,...,...,...,...,...,...,...,...,...,...
886,887,0.0,2.0,"Montvila, Rev. Juozas",male,27.0,0.0,0,211536,13.0000
887,888,1.0,1.0,"Graham, Miss. Margaret Edith",female,19.0,0.0,0,112053,30.0000
888,889,0.0,3.0,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1.0,2,W./C. 6607,23.4500
889,890,1.0,1.0,"Behr, Mr. Karl Howell",male,26.0,0.0,0,111369,30.0000
890,891,0.0,3.0,"Dooley, Mr. Patrick",male,32.0,0.0,0,370376,7.7500

In [451]:
df["Fare"].mean().round(2) #display mean of column Fare

24.04

# 5) Impute missing value



*   Show the number of missing values in each variable
*   Impute missing values with mean & mode
*   Show the number of missing values again after missing value imputation

<font color='blue'>Q5) Which variable has the largest number of missing values?</font>

In [452]:
df.isnull().sum() #show number of missing value each column

PassengerId      0
Survived         0
Pclass          63
Name            25
Sex              0
Age            172
SibSp           33
Parch            0
Ticket          39
Fare             0
dtype: int64

In [453]:
df[["Pclass","Age","SibSp"]] = df[["Pclass","Age","SibSp"]].fillna(df.median())
df = df.fillna(df.mean())

<ipython-input-453-9a05fc0f3f7f>:1: FutureWarning: The default value of numeric_only in DataFrame.median is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df[["Pclass","Age","SibSp"]] = df[["Pclass","Age","SibSp"]].fillna(df.median())
<ipython-input-453-9a05fc0f3f7f>:2: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df = df.fillna(df.mean())

In [454]:
df.isnull().sum() #show number of missing value after imputation

PassengerId     0
Survived        0
Pclass          0
Name           25
Sex             0
Age             0
SibSp           0
Parch           0
Ticket         39
Fare            0
dtype: int64

In [455]:
df #show table

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare
0,1,0.0,3.0,"Braund, Mr. Owen Harris",male,22.0,1.0,0,A/5 21171,7.2500
1,2,1.0,1.0,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1.0,0,PC 17599,65.6563
2,3,1.0,3.0,"Heikkinen, Miss. Laina",female,26.0,0.0,0,STON/O2. 3101282,7.9250
3,4,1.0,1.0,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1.0,0,113803,53.1000
4,5,0.0,3.0,"Allen, Mr. William Henry",male,35.0,0.0,0,373450,8.0500
...,...,...,...,...,...,...,...,...,...,...
886,887,0.0,2.0,"Montvila, Rev. Juozas",male,27.0,0.0,0,211536,13.0000
887,888,1.0,1.0,"Graham, Miss. Margaret Edith",female,19.0,0.0,0,112053,30.0000
888,889,0.0,3.0,"Johnston, Miss. Catherine Helen ""Carrie""",female,28.0,1.0,2,W./C. 6607,23.4500
889,890,1.0,1.0,"Behr, Mr. Karl Howell",male,26.0,0.0,0,111369,30.0000
890,891,0.0,3.0,"Dooley, Mr. Patrick",male,32.0,0.0,0,370376,7.7500

# 6) Convert categorical to numeric values



*   Drop the variables “Name” & “Ticket”
*   For the variables “Sex” & “Embarked”, perform the dummy coding and drop the first level. Also, drop those original variables (“Sex” & “Embarked”)

<font color='blue'>Q6) How many columns do we have?</font>

In [456]:
df = df.drop(["Name","Ticket"],axis=1) #drop name and ticket column
nominal_columns = ["Sex"] #set Sex to nominal category
dummy_df = pd.get_dummies(df[nominal_columns], drop_first=True) #set Sex column to dummy_code
df_dummy = pd.concat([df, dummy_df], axis=1)
df_dummy = df_dummy.drop(nominal_columns, axis=1)
df_dummy #show table

     PassengerId  Survived  Pclass   Age  SibSp  Parch     Fare  Sex_male
0              1       0.0     3.0  22.0    1.0      0   7.2500         1
1              2       1.0     1.0  38.0    1.0      0  65.6563         0
2              3       1.0     3.0  26.0    0.0      0   7.9250         0
3              4       1.0     1.0  35.0    1.0      0  53.1000         0
4              5       0.0     3.0  35.0    0.0      0   8.0500         1
..           ...       ...     ...   ...    ...    ...      ...       ...
886          887       0.0     2.0  27.0    0.0      0  13.0000         1
887          888       1.0     1.0  19.0    0.0      0  30.0000         0
888          889       0.0     3.0  28.0    1.0      2  23.4500         0
889          890       1.0     1.0  26.0    0.0      0  30.0000         1
890          891       0.0     3.0  32.0    0.0      0   7.7500         1

[865 rows x 8 columns]

In [457]:
df_dummy.shape[1] #show column do we have

8

# 7) Partition data



*   Split train/test split with stratification using 70%:30% and random seed with 12345
*   Show a proportion between survived (1) and died (0) in all data sets (total data, train, test)

<font color='blue'>Q7) What is a proportion between survived (1) and died (0) in the training data?</font>

In [458]:
from sklearn.model_selection import train_test_split

In [459]:
df.Survived.value_counts() / df.shape[0]
y = df.pop("Survived")
X = df

X_train,X_test,y_train,y_test = train_test_split(X,y,stratify=y,test_size=0.30, random_state=12345)

In [460]:
X_train #show table

     PassengerId  Pclass     Sex    Age  SibSp  Parch     Fare
305          306     1.0    male   0.92    1.0      2  65.6563
879          880     1.0  female  56.00    0.0      1  65.6563
381          382     3.0  female   1.00    0.0      2  15.7417
491          492     3.0    male  21.00    0.0      0   7.2500
1              2     1.0  female  38.00    1.0      0  65.6563
..           ...     ...     ...    ...    ...    ...      ...
362          363     3.0  female  45.00    0.0      1  14.4542
247          248     2.0  female  24.00    0.0      2  14.5000
331          332     1.0    male  45.50    0.0      0  28.5000
110          111     1.0    male  47.00    0.0      0  52.0000
45            46     3.0    male  28.00    0.0      0   8.0500

[605 rows x 7 columns]

In [461]:
X_train.shape[0] #row of training data

605

In [462]:
X_test #show table of test data

     PassengerId  Pclass     Sex   Age  SibSp  Parch     Fare
807          808     3.0  female  18.0    0.0      0   7.7750
324          325     3.0    male  28.0    8.0      2  65.6563
389          390     2.0  female  17.0    0.0      0  12.0000
329          330     1.0  female  16.0    0.0      1  57.9792
779          780     1.0  female  43.0    0.0      1  65.6563
..           ...     ...     ...   ...    ...    ...      ...
10            11     3.0  female   4.0    1.0      1  16.7000
502          503     3.0  female  28.0    0.0      0   7.6292
0              1     3.0    male  22.0    1.0      0   7.2500
223          224     3.0    male  28.0    0.0      0   7.8958
218          219     1.0  female  32.0    0.0      0  65.6563

[260 rows x 7 columns]

In [463]:
X_test.shape[0] #row of test data

260

In [464]:
y_train.value_counts() / y_train.shape[0]

0.0    0.616529
1.0    0.383471
Name: Survived, dtype: float64

In [465]:
y_test.value_counts() / y_test.shape[0]

0.0    0.615385
1.0    0.384615
Name: Survived, dtype: float64